# -*- coding: utf-8 -*-

C ||= CONFIG = {}

C[:USER]  ||= ENV['USER']  || 'unknown_user'
C[:REPOS] ||= ENV['REPOS'] || File.basename(Dir.pwd)

desc 'Build an image'
task :build do |t|
  sh "docker build --tag=#{C[:USER]}/#{C[:REPOS]} ."
end

desc 'Remove the image'
task :clean do |t|
  sh "docker rmi #{C[:USER]}/#{C[:REPOS]}; echo Info: exit status: $?"
end

task :default => :build
